package dev.lochert.ds.blockchain.http.server.malicious

import dev.lochert.ds.blockchain.http.server.Server
import dev.lochert.ds.blockchain.pki.RSAKeyPairs
import java.net.ServerSocket

var counter: UShort = 9000U

fun main() {
    try {
        val ownPort = counter
        if (isPortAvailable(ownPort.toInt())) {
            // If the port is available, start the server
            val s = Server()
            repeat(15) {
                s.blockChain.addBlock("MaliciousTx-$it", miner = RSAKeyPairs.mallory.publicKeyToString())
            }
            s.addressList.addAddress("172.18.0.3", 9000u)
            s.startServer()
        } else {
            throw RuntimeException("Port $ownPort is already in use")
        }
    } catch (e: RuntimeException) {
        println("Trying next port ${++counter}")
        main()
    }
}

// Generated by ChatGPT
// Function to check if the port is available
fun isPortAvailable(port: Int): Boolean {
    return try {
        val serverSocket = ServerSocket(port)
        serverSocket.close()  // Close the socket immediately if the port is available
        true  // Port is available
    } catch (e: Exception) {
        false  // Port is already in use
    }
}
